# # name: nodejs_mysql

# # on:
# #   push:
# #     branches: [main]

# # jobs:
# #   docker:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout
# #         uses: actions/checkout@v3

# #       - name: Login to Docker Hub
# #         uses: docker/login-action@v2
# #         with:
# #           username: ${{ secrets.DOCKER_HUB_USERNAME }}
# #           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

# #       - name: Build and Push Docker Image
# #         uses: docker/build-push-action@v4
# #         id: docker_build
# #         with:
# #           context: ./
# #           # file: ./Dockerfile
# #           # builder: ${{ steps.buildx.outputs.name }}
# #           push: true
# #           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nodejsapi:latest

# #       - name: Verify Digest
# #         run: echo "${{ steps.docker_build.outputs.digest }}"
# name: nodejs_mysql

# on:
#   push:
#     branches: [main]

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Build and Push Docker Image
#         uses: docker/build-push-action@v4
#         with:
#           context: ./
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nodejsapi:latest

#       - name: Verify Digest
#         run: echo "${{ steps.docker_build.outputs.digest }}"

name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 123456789
          MYSQL_DATABASE: nodejsapi
        ports:
          - 3307:3306

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (for multi-platform builds, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t maiquochuy/nodejsapi .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push maiquochuy/nodejsapi
